server:
  port: 8080

spring:
  config:
    import: "optional:configserver:http://localhost:8071/"
  datasource:
    url: jdbc:mysql://10.0.0.32:3306/accounts
    username: docker
    password: docker
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: "prod"
  application:
    name: "accounts"

springdoc:
  swagger-ui:
    path: /swagger-ui.html

build:
  version: "2.0-dev"