server:
  port: 9010

spring:
  application:
    name: "message"
  profiles:
    active: default
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    stream:
      kafka:
        binder:
          brokers:
            - localhost:9092