server:
  port: 8082

spring:
  application:
    name: "eureka-server"
  profiles:
    active: "local"
  config:
    import: "optional:configserver:http://localhost:8071/"




#Run springboot from command line passing the profile
#mvn spring-boot:run -D"spring-boot.run.profiles"=dev