server:
  port: 8071

spring:
  application:
    name: "config-server"
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/azeez-bammeke/webnet-config.git"
          default-label: master
          timeout: 5
          clone-on-start: true
          force-pull: true


encrypt:
  key: "*sCUX{MZR(+AC.B<t<a)SnG'h:BzXX{]"