#can define any number of service
services:
  config-server:
    image: "abammeke/config-server:config-server-v4"
    container_name: config-server
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: "abammeke/accounts:accounts-v4"
    container_name: account-services
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: accounts
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  eurekaserver:
    image: "abammeke/eurekaserver:eurekaserver-v4"
    container_name: eurekaserver
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: eurekaserver
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8071/
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loans:
    image: "abammeke/loans:loans-v4"
    container_name: loan-services
    ports:
      - "8082:8082"
    environment:
      SPRING_APPLICATION_NAME: loans
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  cards:
    image: "abammeke/cards:cards-v4"
    container_name: cards-services
    ports:
      - "8081:8081"
    environment:
      SPRING_APPLICATION_NAME: cards
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  webnet:
    driver: "bridge"