server:
  port: 8072

spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"

logging:
  level:
    com:
      webnet:
        gatewayserver: DEBUG