server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://10.0.0.32:3306/cards
    username: docker
    password: docker
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import:
     - "applications-dev.yml"
     - "applications-prod.yml"
springdoc:
  swagger-ui:
    path: /swagger-ui.html


build:
  version: "2.8-card-local"
