services:
  network-deploy-service:
    networks:
      - webnet

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m

  microservice-configserver-config:
    extends:
      service: microservice-base-config
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8071/"

